
- name: "SSH public key for '{{ item }}'"
  authorized_key:
    user: "{{ item }}"
    state: "present"
    key: "{{ lookup('file', '~/.ssh/{{ items }}.id_rsa.pub') }}"
  with_items: "{{ all_users }}"
  tags: setup_keys

