---

- name: "Set hostname to {{ bastion_hostname }}"
  hostname:
    name: "{{ bastion_hostname }}"
  tags:
    - notest

- name: Check dhcpcd service is started and enabled
  service:
    name: dhcpcd
    state: started
    enabled: true
  tags:
    - notest

- name: "Set static IP for {{ dhcpcd_interface }}"
  template:
    src: dhcpcd.conf.j2
    dest: "{{ dhcpcd_conf_location }}"
    mode: "0644"
  notify: reboot system
  tags:
    - notest

- name: Force handler to be executed
  meta: flush_handlers
  tags:
    - notest

...
