---

- name: Verify
  hosts: all
  tasks:
  - name: Example assertion
    assert:
      that: true

# don't verify the hostname (limitation in docker)
# verify that dhcpcd is running
# verify dhcpcd.conf contains correct values

...