

- name: "Create user accounts and add users to groups"
  user:
    name: "{{ item }}"
    create_home: yes
    password: "{{ 'changeme' | password_hash('sha512') }}" 
    update_password: always
    groups: "www-data"
  with_items: "{{ users }}"
  tags: installation, setup, users
