

- name: "Update Apt Cache"
  apt: 
    update_cache: yes
  tags: installation

- name: "Install Common packages"
  apt:
    name: ['vim', 'nano', 'htop', 'git', 'screen', 'net-tools']
    state: latest
  tags: installation, packages
